config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  devise_for :admins, skip: :all
  devise_scope :admin do
    get 'admins/sign_in' => 'admins/sessions#new', as: 'new_admin_session'
    post 'admins/sign_in' => 'admins/sessions#create', as: 'admin_session'
    delete 'admins/sign_out' => 'admins/sessions#destroy', as: 'destroy_admin_session'
  end


  namespace :admins do
    get 'requests/her_requests/:id' => 'requests#her_requests', as: 'her_requests'
    resources :requests, only: [:index, :show, :edit, :update] do
      collection do
        get 'search'
      end
    end
    get 'posts/her_posts/:id' => 'posts#her_posts', as: 'her_posts'
    resources :posts, only: [:index, :show, :update] do
      resources :post_comments, only: [:update]
    end
    get 'users/:id/rooms' => 'rooms#index', as: 'her_rooms'
    get 'users/:id/rooms/:id' => 'rooms#show', as: 'her_room'
    resources :users, only: [:index, :show, :edit, :update] do
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
  end

  scope module: :public do
    root 'homes#top'
    get '/about' => 'homes#about'
    get '/result' => 'homes#result'
    get '/privacy_policy' => 'homes#privacy'
    get 'users/my_page' => 'users#show'
    get 'users/unsubscribe' => 'users#unsubscribe'
    patch 'users/withdraw' => 'users#withdraw'
    resources :users, only: [:edit, :update] do
      resources :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end

    get 'contact' => 'contacts#new'
    post 'contact/confirm' => 'contacts#confirm'
    post 'contact/thanks' => 'contacts#thanks'

    resources :rooms, only: [:create, :show, :index]
    resources :messages, only: [:create]
    get 'requests/her_requests/:id' => 'requests#her_requests', as: 'her_requests'
    resources :requests, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      collection do
        get 'search'
      end
    end
    get 'posts/her_posts/:id' => 'posts#her_posts', as: 'her_posts'
    resources :posts, only: [:new, :create, :index, :show, :destroy] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
  end

  devise_for :users, skip: [:sessions, :registrations, :passwords], controllers: {
    omniauth_callbacks: 'public/omniauth_callbacks'
  }
  devise_scope :user do
    get 'users/sign_up' => 'public/registrations#new', as: 'new_user_registration'
    post 'users' => 'public/registrations#create', as: 'user_registration'
    get 'users/sign_in' => 'public/sessions#new', as: 'new_user_session'
    post 'users/sign_in' => 'public/sessions#create', as: 'user_session'
    delete 'users/sign_out' => 'public/sessions#destroy', as: 'destroy_user_session'
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/controllers/admins/rooms_controller.rb
class Admins::RoomsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @user = User.find(params[:id])
    @entries = Entry.where(user_id: @user).page(params[:page])
  end

  def show
    @room = Room.find(params[:id])
    @messages = @room.messages
    @entries = @room.entries
    @user = User.find(params[:id])
  end
end

app/helpers/admins/rooms_helper.rb
module Admins::RoomsHelper
end

app/views/admins/rooms/index.html.erb
<div class="belt-admin"></div>
<div class='container'>
  <div class='row'>
    <div class='col-md-12 col-lg-12'>
    <h4>Chats</h4>
    <% if @entries.exists? %>
    <table cellpadding="10" class='table table-hover table-inverse rowtable-index'>
      <thead>
        <tr style="background-color: #EEEEEE;" class="tr-border">
          <th colspan="1">更新日</th>
          <th>名前</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @entries.each do |entry| %>
        <tr class="tr-border">
          <td data-title="更新"><%= entry.room.updated_at.strftime("%Y-%m-%d %H:%M") %></td>
          <td data-title="名前"><%= entry.room.entries.find{ |e| e.user_id != @user.id }.user.name %>さん</td>
          <td><%= link_to 'チャットへ', admins_her_room_path(entry.room), data: {"turbolinks" => false}, class: "btn btn-link request_#{entry.room.id}" %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <div class="pagination"><%= paginate @entries %></div>
    <% else %>
      <p>チャットはありません</p>
    <% end %>
    </div>
  </div>
</div>

app/views/admins/rooms/show.html.erb
<div class="belt-admin"></div>
<div class='container'>
  <h4>
    Chat Room of
    <% @entries.each_with_index do |e, idx| %>
      <%= e.user.name %>
      <% if idx == 0 %>
        and
      <% end %>
    <% end %>
  </h4>
  <button class="btn btn-link arrowbtn">
    <i class="fa fa-arrow-down arrow"></i>
  </button>
  <% @messages.each do |message| %>
  <div class='row chat-box'>
    <div class='col-md-2 col-lg-2 d-flex align-items-center justify-content-center'>
      <%= attachment_image_tag message.user, :image, format: 'jpeg', fallback: "no_image.jpg", class: "chat-user-img" %>
    </div>
    <div class='col-md-10 col-lg-10 text-left'>
      <span><strong><%= message.user.name %></strong></span>
      <span class="date"><%= message.created_at.strftime("%Y-%m-%d %H:%M")%></span>
      <p><%= message.content %></p>
    </div>
  </div>
  <% end %>
</div>