config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  devise_for :admins, skip: :all
  devise_scope :admin do
    get 'admins/sign_in' => 'admins/sessions#new', as: 'new_admin_session'
    post 'admins/sign_in' => 'admins/sessions#create', as: 'admin_session'
    delete 'admins/sign_out' => 'admins/sessions#destroy', as: 'destroy_admin_session'
  end


  namespace :admins do
    get 'requests/her_requests/:id' => 'requests#her_requests', as: 'her_requests'
    resources :requests, only: [:index, :show, :edit, :update] do
      collection do
        get 'search'
      end
    end
    get 'posts/her_posts/:id' => 'posts#her_posts', as: 'her_posts'
    resources :posts, only: [:index, :show, :update] do
      resources :post_comments, only: [:update]
    end
    get 'users/:id/rooms' => 'rooms#index', as: 'her_rooms'
    get 'users/:id/rooms/:id' => 'rooms#show', as: 'her_room'
    resources :users, only: [:index, :show, :edit, :update] do
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
  end

  scope module: :public do
    root 'homes#top'
    get '/about' => 'homes#about'
    get '/result' => 'homes#result'
    get '/privacy_policy' => 'homes#privacy'
    get 'users/my_page' => 'users#show'
    get 'users/unsubscribe' => 'users#unsubscribe'
    patch 'users/withdraw' => 'users#withdraw'
    resources :users, only: [:edit, :update] do
      resources :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end

    get 'contact' => 'contacts#new'
    post 'contact/confirm' => 'contacts#confirm'
    post 'contact/thanks' => 'contacts#thanks'

    resources :rooms, only: [:create, :show, :index]
    resources :messages, only: [:create]
    get 'requests/her_requests/:id' => 'requests#her_requests', as: 'her_requests'
    resources :requests, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      collection do
        get 'search'
      end
    end
    get 'posts/her_posts/:id' => 'posts#her_posts', as: 'her_posts'
    resources :posts, only: [:new, :create, :index, :show, :destroy] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
  end

  devise_for :users, skip: [:sessions, :registrations, :passwords], controllers: {
    omniauth_callbacks: 'public/omniauth_callbacks'
  }
  devise_scope :user do
    get 'users/sign_up' => 'public/registrations#new', as: 'new_user_registration'
    post 'users' => 'public/registrations#create', as: 'user_registration'
    get 'users/sign_in' => 'public/sessions#new', as: 'new_user_session'
    post 'users/sign_in' => 'public/sessions#create', as: 'user_session'
    delete 'users/sign_out' => 'public/sessions#destroy', as: 'destroy_user_session'
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[facebook google_oauth2]
  attachment :image
  has_many :requests
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  validates :name, presence: true, length: { maximum: 50 }
  validates :introduction, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, uniqueness: true, format: { with: VALID_EMAIL_REGEX }, length: { maximum: 250 }


  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.name = auth.info.name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  def self.guest
    find_or_create_by!(name: 'guest', email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end

  def update
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admins_users_path
    else
      render 'edit'
    end
  end

  private
    def user_params
      params.require(:user).permit(:image, :name, :email, :introduction, :is_valid)
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admins/users/edit.html.erb
<div class="belt-admin"></div>
<div class='container'>
  <div class='row'>
    <div class='col-md-12 col-lg-12'>
    <%= render 'error/edit_message', model: @user %>
    <h4>Edit user</h4>
    <br>
    <br>
    <%= form_with model: @user,url: admins_user_path(@user), local: true do |f| %>
      <table cellpadding="10" class="rowtable">
        <tr>
          <td>
            <div class="edit-user-img text-center">
              <%= attachment_image_tag @user, :image, format: 'jpeg', fallback: "no_image.jpg", class: "user-img" %>
            </div>
          </td>
          <td colspan="3">
            <%= f.attachment_field :image, class: "user-img-btn" %>
          </td>
        </tr>
        <tr>
          <td>会員ID</td>
          <td colspan="3"><%= @user.id %></td>
        </tr>        <tr>
          <td>氏名</td>
          <td colspan="3"><%= f.text_field :name, class: "text-form" %></td>
        </tr>
        <tr>
          <td>メールアドレス</td>
          <td colspan="3"><%= f.text_field :email, class: "text-form" %></td>
        </tr>
        <tr>
          <td>一言</td>
          <td colspan="3"><%= f.text_area :introduction, :size => "45", class: "text-form" %></td>
        </tr>
        <tr>
          <td>ステータス</td>
          <td colspan="3">
            <span><%= f.radio_button :is_valid, :true %><%= f.label :true, "有効" %></span>&emsp;&emsp;
            <span><%= f.radio_button :is_valid, :false %><%= f.label :false, "退会" %></span>
          </td>
        </tr>
        <tr>
          <td></td>
          <td><%= f.submit "　編集内容を保存　", class: "btn btn-outline-secondary" %></td>
          <td></td>
          <td></td>
        </tr>
      </table>
    <% end %>
    </div>
  </div>
</div>

app/views/admins/users/index.html.erb
<div class="belt-admin"></div>
<div class='container'>
  <div class='row'>
    <div class='col-md-12 col-lg-12'>
    <h4>Users</h4>
    <table cellpadding="10" class='table table-hover table-inverse rowtable-index'>
      <thead>
        <tr style="background-color: #EEEEEE;" class="tr-border">
          <th>会員ID</th>
          <th colspan="2">名前</th>
          <th colspan="2">メールアドレス</th>
          <th>依頼数</th>
          <th>投稿数</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
    　　<% @users.each do |user| %>
        <tr class="tr-border">
          <td><%= user.id %></td>
          <td colspan="2" data-title="名前"><%= link_to truncate(user.name, length:25), admins_user_path(user), class: "btn btn-link" %></td>
          <td colspan="2" data-title="メールアドレス"><%= truncate(user.email, length:25) %></td>
          <td data-title="依頼数"><%= user.requests.count %></td>
          <td data-title="投稿数"><%= user.posts.count %></td>
          <td>
            <% if user.is_valid %>
              <div>有効</div>
            <% else %>
              <div style="color: gray;">退会</div>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <div class="pagination"><%= paginate @users %></div>
    </div>
  </div>
</div>

app/views/admins/users/show.html.erb
<div class="belt-admin"></div>
<div class='container'>
  <h4>User info</h4>
  <div class="text-right"><%= link_to '編集する', edit_admins_user_path(@user), class: "btn btn-outline-secondary" %></div>
  <div class='row admin-user-table rowtable'>
    <div class='col-md-4 col-lg-4 d-flex align-items-center justify-content-center'>
      <div><%= attachment_image_tag @user, :image, format: 'jpeg', fallback: "no_image.jpg", class: "user-img" %></div>
    </div>
    <div class='col-md-8 col-lg-8'>
      <table cellpadding="10" class="user-info">
        <tr class="tr-border">
          <td>会員ID</td>
          <td><%= @user.id %></td>
        </tr>
        <tr class="tr-border">
          <td>表示名</td>
          <td><%= @user.name %></td>
        </tr>
        <tr class="tr-border">
          <td>メールアドレス</td>
          <td><%= @user.email %></td>
        </tr>
        <tr class="tr-border">
          <td>一言</td>
          <td><%= @user.introduction %></td>
        </tr>
        <tr class="tr-border">
          <td>ステータス</td>
          <td>
            <% if @user.is_valid %>
              <div>有効</div>
            <% else %>
              <div style="color: gray;">退会</div>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>
  <div class='row'>
    <div class='col-md-12 col-lg-12 admin-flowers'>
      <div class="img">
        <%= link_to admins_her_rooms_path do %>
          <%= image_tag "pinkflower2.jpg" %>
          <div class="admin-mask">
            <p>チャット一覧</p>
          </div>
        <% end %>
      </div>
      <div class="img">
        <%= link_to admins_her_requests_path(@user) do %>
          <%= image_tag "greenflower.jpg" %>
          <div class="admin-mask">
            <p>依頼履歴一覧</p>
          </div>
        <% end %>
      </div>
      <div class="img">
        <%= link_to admins_her_posts_path(@user) do %>
          <%= image_tag "blueflower.jpg" %>
          <div class="admin-mask">
            <p>投稿一覧</p>
          </div>
        <% end %>
      </div>
      <div class="img">
        <%= link_to admins_user_followings_path(@user) do %>
          <%= image_tag "yellowflower.jpg" %>
          <div class="admin-mask">
            <p>フォロー一覧</p>
          </div>
        <% end %>
      </div>
      <div class="img">
        <%= link_to admins_user_followers_path(@user) do %>
          <%= image_tag "orangeflower.jpg" %>
          <div class="admin-mask">
            <p>フォロワー一覧</p>
          </div>
        <% end %>
      </div>
      <div class="blank"></div>
    </div>
  </div>
</div>