config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  devise_for :admins, skip: :all
  devise_scope :admin do
    get 'admins/sign_in' => 'admins/sessions#new', as: 'new_admin_session'
    post 'admins/sign_in' => 'admins/sessions#create', as: 'admin_session'
    delete 'admins/sign_out' => 'admins/sessions#destroy', as: 'destroy_admin_session'
  end


  namespace :admins do
    get 'requests/her_requests/:id' => 'requests#her_requests', as: 'her_requests'
    resources :requests, only: [:index, :show, :edit, :update] do
      collection do
        get 'search'
      end
    end
    get 'posts/her_posts/:id' => 'posts#her_posts', as: 'her_posts'
    resources :posts, only: [:index, :show, :update] do
      resources :post_comments, only: [:update]
    end
    get 'users/:id/rooms' => 'rooms#index', as: 'her_rooms'
    get 'users/:id/rooms/:id' => 'rooms#show', as: 'her_room'
    resources :users, only: [:index, :show, :edit, :update] do
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
  end

  scope module: :public do
    root 'homes#top'
    get '/about' => 'homes#about'
    get '/result' => 'homes#result'
    get '/privacy_policy' => 'homes#privacy'
    get 'users/my_page' => 'users#show'
    get 'users/unsubscribe' => 'users#unsubscribe'
    patch 'users/withdraw' => 'users#withdraw'
    resources :users, only: [:edit, :update] do
      resources :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end

    get 'contact' => 'contacts#new'
    post 'contact/confirm' => 'contacts#confirm'
    post 'contact/thanks' => 'contacts#thanks'

    resources :rooms, only: [:create, :show, :index]
    resources :messages, only: [:create]
    get 'requests/her_requests/:id' => 'requests#her_requests', as: 'her_requests'
    resources :requests, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      collection do
        get 'search'
      end
    end
    get 'posts/her_posts/:id' => 'posts#her_posts', as: 'her_posts'
    resources :posts, only: [:new, :create, :index, :show, :destroy] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
  end

  devise_for :users, skip: [:sessions, :registrations, :passwords], controllers: {
    omniauth_callbacks: 'public/omniauth_callbacks'
  }
  devise_scope :user do
    get 'users/sign_up' => 'public/registrations#new', as: 'new_user_registration'
    post 'users' => 'public/registrations#create', as: 'user_registration'
    get 'users/sign_in' => 'public/sessions#new', as: 'new_user_session'
    post 'users/sign_in' => 'public/sessions#create', as: 'user_session'
    delete 'users/sign_out' => 'public/sessions#destroy', as: 'destroy_user_session'
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  enum urgency: { high: 0, middle: 1, low: 2 }
  enum genre: { other: 0, sanitary: 1, cloth: 2, hygiene: 3, child: 4 }
  is_impressionable counter_cache: true
  validates :item, presence: true, length: { maximum: 50 }
  validates :quantity, presence: true, length: { maximum: 50 }
  validates :comment, length: { maximum: 255 }
  validates :postal_code, length: { is: 7 }, allow_blank: true
  validates :location, length: { maximum: 250 }
  validates :phone_number, length: { maximum: 11 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, length: { maximum: 250 }, format: { with: VALID_EMAIL_REGEX }, allow_blank: true
  validates :name, length: { maximum: 50 }
end

app/controllers/admin/requests_controller.rb
class Admin::RequestsController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end

  def update
  end
end

app/controllers/admins/requests_controller.rb
class Admins::RequestsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_q, only: [:index, :search]

  def index
    @requests = @q.result.page(params[:page])
  end

  def show
    @request = Request.find(params[:id])
  end

  def edit
    @request = Request.find(params[:id])
  end

  def update
    @request = Request.find(params[:id])
    if @request.update(request_params)
      redirect_to admins_requests_path
    else
      render 'edit'
    end
  end

  def her_requests
    @user = User.find(params[:id])
    @requests = Request.where(user_id: @user.id).page(params[:page])
  end

  def search
    @results = @q.result.page(params[:page])
  end


  private
    def set_q
      @q = Request.ransack(params[:q])
    end

    def request_params
      params.require(:request).permit(:urgency, :item, :quantity, :comment, :postal_code, :location, :phone_number, :email, :name, :is_done, :genre)
    end

end

app/helpers/admin/requests_helper.rb
module Admin::RequestsHelper
end

app/views/admins/requests/edit.html.erb
<div class="belt-admin"></div>
<div class='container'>
  <div class='row'>
    <div class='col-md-12 col-lg-12'>
    <%= render 'error/edit_message', model: @request %>
    <h4>Edit Request</h4>
    <%= form_with model: @request, url: admins_request_path(@request), local: true do |f| %>
      <table cellpadding="10" class="rowtable">
        <tr>
          <td>緊急性</td>
          <td colspan="3">
            <span><%= f.radio_button :urgency, :high %><%= f.label :high, "高い" %></span>&emsp;&emsp;
            <span><%= f.radio_button :urgency, :middle %><%= f.label :middle, "やや高い" %></span>&emsp;&emsp;
            <span><%= f.radio_button :urgency, :low %><%= f.label :low, "低い" %></span>
          </td>
        </tr>
        <tr>
          <td>種別</td>
          <td colspan="3">
            <span><%= f.radio_button :genre, :other %><%= f.label :other, "その他" %></span>&emsp;&emsp;
            <span><%= f.radio_button :genre, :sanitary %><%= f.label :sanitary, "生理用品" %></span>&emsp;&emsp;
            <span><%= f.radio_button :genre, :cloth %><%= f.label :cloth, "下着・衣類" %></span>&emsp;&emsp;
            <span><%= f.radio_button :genre, :hygiene %><%= f.label :hygiene, "衛生用品・化粧品" %></span>&emsp;&emsp;
            <span><%= f.radio_button :genre, :child %><%= f.label :child, "子ども用品" %></span>
          </td>
        </tr>
        <tr>
          <td>物品名</td>
          <td colspan="3"><%= f.text_field :item, class: "text-form" %></td>
        </tr>
        <tr>
          <td>数量</td>
          <td colspan="3"><%= f.text_field :quantity, class: "text-form" %></td>
        </tr>
        <tr>
          <td>コメント</td>
          <td colspan="3"><%= f.text_area :comment, :size=>"70", class: "text-form" %></td>
        </tr>
        <tr>
          <td>郵便番号</td>
          <td colspan="3"><%= f.text_field :postal_code, class: "text-form" %></td>
        </tr>
        <tr>
          <td>宛先</td>
          <td colspan="3"><%= f.text_field :location, :size=>"70", class: "text-form" %></td>
        </tr>
        <tr>
          <td>電話番号</td>
          <td colspan="3"><%= f.text_field :phone_number, class: "text-form" %></td>
        </tr>
        <tr>
          <td>メールアドレス</td>
          <td colspan="3"><%= f.text_field :email, class: "text-form" %></td>
        </tr>
        <tr>
          <td>宛名</td>
          <td colspan="3"><%= f.text_field :name, class: "text-form" %></td>
        </tr>
        <tr>
          <td>ステータス</td>
          <td colspan="3">
            <span><%= f.radio_button :is_done, :false %><%= f.label :false, "依頼中" %></span>&emsp;&emsp;
            <span><%= f.radio_button :is_done, :true %><%= f.label :true, "お届け完了" %></span>
          </td>
        </tr>
        <tr>
          <td></td>
          <td><%= f.submit "変更を保存", class: "btn btn-outline-secondary" %></td>
          <td></td>
          <td></td>
        </tr>
      </table>
    <% end %>
    </div>
  </div>
</div>

app/views/admins/requests/her_requests.html.erb
<div class="belt-admin"></div>
<div class='container'>
  <div class='row'>
    <div class='col-md-12 col-lg-12'>
    <h4><%= @user.name %>'s Requests</h4>
    <% if @requests.exists? %>
    <div class="jscroll">
    <table cellpadding="10" class='table table-hover table-inverse content rowtable-index'>
      <thead>
        <tr style="background-color: #EEEEEE;" class="tr-border">
          <th colspan="1">依頼日</th>
          <th>物品名</th>
          <th>数量</th>
          <th>緊急性</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @requests.each do |request| %>
        <tr class="tr-border">
          <td><%= link_to request.created_at.strftime("%Y-%m-%d %H:%M"), admins_request_path(request), class: "btn btn-link request_#{request.id}" %></td>
          <td data-title="物品名"><%= request.item %></td>
          <td data-title="数量"><%= request.quantity %></td>
          <td data-title="緊急性"><%= request.urgency_i18n %></td>
          <td>
            <% if request.is_done %>
              <div style="color: gray;">お届け完了</div>
            <% else %>
              <div>依頼中</div>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <div class="pagination"><%= paginate @requests %></div>
    </div>
    <% else %>
      <p>依頼はありません</p>
    <% end %>
    </div>
  </div>
</div>

app/views/admins/requests/index.html.erb
<div class="belt-admin"></div>
<div class='container'>
  <div class='row'>
    <div class='col-md-12 col-lg-12'>
    <h4>Requests</h4>
    <div class="open">
      <a style="cursor:pointer;"><i class="fas fa-search loupe"></i></a>
    </div>
    <div class="hidden">
      <div class="search-btn">
        <%= search_form_for @q, url: search_admins_requests_path do |f| %>
          <%= f.label :urgency_eq, '<緊急性>' %>
          <%= f.radio_button :urgency_eq, '' %>指定しない&emsp;
          <%= f.radio_button :urgency_eq, 0 %><%= f.label :high, "高い" %>&emsp;
          <%= f.radio_button :urgency_eq, 1 %><%= f.label :middole, "やや高い" %>&emsp;
          <%= f.radio_button :urgency_eq, 2 %><%= f.label :low, "低い" %><br>
          <%= f.label :genre_eq, '<種別>' %>
          <%= f.radio_button :genre_eq, '' %>指定しない&emsp;
          <%= f.radio_button :genre_eq, 0 %><%= f.label :other, "その他" %>&emsp;
          <%= f.radio_button :genre_eq, 1 %><%= f.label :sanitary, "生理用品" %>&emsp;
          <%= f.radio_button :genre_eq, 2 %><%= f.label :cloth, "下着・衣類" %>&emsp;
          <%= f.radio_button :genre_eq, 3 %><%= f.label :hygiene, "衛生用品・化粧品" %>&emsp;
          <%= f.radio_button :genre_eq, 4 %><%= f.label :child, "子ども用品" %><br>
          <%= f.search_field :item_or_location_or_name_or_postal_code_or_comment_cont, placeholder: "(例)神奈川県" %>
          <%= f.submit '検索', class: "btn btn-sm btn-outline-secondary" %>
        <% end %>
      </div>
    </div>
    <table cellpadding="10" class='table table-hover table-inverse request-index-table rowtable-index'>
      <thead>
        <tr style="background-color: #EEEEEE;" class="tr-border">
          <th colspan="2"><%= sort_link(@q, :created_at, "依頼日", default_order: :desc) %></th>
          <th colspan="2">依頼者</th>
          <th colspan="2">物品名</th>
          <th colspan="2">数量</th>
          <th><%= sort_link(@q, :urgency, "緊急性", default_order: :desc) %></th>
          <th colspan="2">ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @requests.each do |request| %>
        <tr class="tr-border">
          <td colspan="2"><%= link_to request.created_at.strftime("%Y-%m-%d %H:%M"), admins_request_path(request), class: "btn btn-link admins_request_#{request.id}" %></td>
          <td colspan="2" data-title="依頼者"><%= truncate(request.user.name) %></td>
          <td colspan="2" data-title="物品名"><%= truncate(request.item) %></td>
          <td colspan="2" data-title="数量"><%= truncate(request.quantity) %></td>
          <td data-title="緊急性"><%= request.urgency_i18n %></td>
          <td colspan="2">
            <% if request.is_done %>
              <div style="color: gray;">お届け完了</div>
            <% elsif !request.user.is_valid %>
              <div style="color: gray;">未了のまま退会</div>
            <% else %>
              <div>依頼中</div>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <div class="pagination"><%= paginate @requests %></div>
    </div>
  </div>
</div>

app/views/admins/requests/search.html.erb
<div class="belt-admin"></div>
<div class='container'>
  <div class='row'>
    <div class='col-md-12 col-lg-12'>
      <h4>Search</h4>
      <% if @results.exists? %>
        <table cellpadding="10" class='table table-hover table-inverse request-index-table rowtable-index'>
          <thead>
            <tr style="background-color: #EEEEEE;" class="tr-border">
              <th colspan="1"><%= sort_link(@q, :created_at, "依頼日", default_order: :desc) %></th>
              <th>物品名</th>
              <th>数量</th>
              <th><%= sort_link(@q, :urgency, "緊急性", default_order: :desc) %></th>
              <th><%= sort_link(@q, :impressions_count, "閲覧数", default_order: :desc) %></th>
            </tr>
          </thead>
          <tbody>
            <% @results.each do |request| %>
              <tr class="tr-border">
                <td><%= link_to request.created_at.strftime("%Y-%m-%d %H:%M"), admins_request_path(request), class: "btn btn-link request_#{request.id}" %></td>
                <td data-title="物品名"><%= request.item %></td>
                <td data-title="数量"><%= request.quantity %></td>
                <td data-title="緊急性"><%= request.urgency_i18n %></td>
                <td data-title="閲覧数"><%= request.impressions_count %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class="pagination"><%= paginate @results %></div>
      <% else %>
        <p>該当する依頼はありません</p>
      <% end %>
    </div>
  </div>
</div>

app/views/admins/requests/show.html.erb
<div class="belt-admin"></div>
<div class='container'>
  <div class='row'>
    <div class='col-md-12 col-lg-12'>
      <h4>Request info</h4>
      <table cellpadding="10" class="show-request-table">
        <tr class="tr-border">
          <th>依頼人</th>
          <td colspan="3"><%= @request.user.name %></td>
        </tr>
        <tr class="tr-border">
          <th>依頼日</th>
          <td colspan="3"><%= @request.created_at.strftime("%Y-%m-%d %H:%M") %></td>
        </tr>
        <tr class="tr-border">
          <th>緊急性</th>
          <td colspan="3"><%= @request.urgency_i18n %></td>
        </tr>
        <tr class="tr-border">
          <th>種別</th>
          <td colspan="3"><%= @request.genre_i18n %></td>
        </tr>
        <tr class="tr-border">
          <th>物品名</th>
          <td colspan="3"><%= @request.item %></td>
        </tr>
        <tr class="tr-border">
          <th>数量</th>
          <td colspan="3"><%= @request.quantity %></td>
        </tr>
        <tr class="tr-border">
          <th>コメント</th>
          <td colspan="3"><%= @request.comment %></td>
        </tr>
        <tr class="tr-border">
          <th>郵便番号</th>
          <td colspan="3"><%= @request.postal_code %></td>
        </tr>
        <tr class="tr-border">
          <th>宛先</th>
          <td colspan="3"><%= @request.location %></td>
        </tr>
        <tr class="tr-border">
          <th>宛名</th>
          <td colspan="3"><%= @request.name %></td>
        </tr>
        <tr class="tr-border">
          <th>電話番号</th>
          <td colspan="3"><%= @request.phone_number %></td>
        </tr>
        <tr class="tr-border">
          <th>メールアドレス</th>
          <td colspan="3"><%= @request.email %></td>
        </tr>
      </table>
      <br>
      <div><%= link_to '編集する', edit_admins_request_path(@request), class: "btn btn-outline-secondary" %></div>
    </div>
  </div>
</div>